{form $form}

<ul n:if="count($formErrors) > 0">
	<li n:foreach="$formErrors as $error">{$error}</li>
</ul>

<table>
	<tr>
		<td>{label name}Název{/label}</td>
		<td>{input name size => 50, style => "font-size: 140%"}</td>
	</tr><tr>
		<td>{label url}URL{/label}</td>
		<td>{input url size => 50}</td>
	</tr><tr>
		<td style="max-width: 130px;">{label description}Popis (viditelný ve vyhledávačích u výsledku vyhledávání){/label}</td>
		<td>{input description size => 90}</td>
	</tr><tr>
		<td>{label text}Text{/label}</td>
		<td>{input text rows => 20, cols => 90}</td>
	</tr><tr>
		<td></td>
		<td>{input allowed} {label allowed}Povolit samostatné zobrazení jako článek{/label}</td>
	</tr>
</table>

<p>{input s value => "Uložit"}</p>

{/form}