{form $form}

<ul n:if="count($formErrors) > 0">
	<li n:foreach="$formErrors as $error">{$error}</li>
</ul>

<table>
	<tr>
		<td>{label name text => "Název"}</td>
		<td>{input name size => 50, style => "font-size: 140%"}</td>
	</tr><tr>
		<td>{label url text => "URL"}</td>
		<td>{input url size => 50}</td>
	</tr><tr>
		<td style="max-width: 130px;">{label description text => "Popis (viditelný ve vyhledávačích u výsledku vyhledávání)"}</td>
		<td>{input description size => 90}</td>
	</tr><tr>
		<td>{label text text => "Text"}</td>
		<td>{input text rows => 20, cols => 90}</td>
	</tr><tr>
		<td></td>
		<td>{input allowed} {label allowed text => "Povolit samostatné zobrazení jako článek"}</td>
	</tr>
</table>

<p>{input s value => "Uložit"}</p>

{/form}