{form $form}

<fieldset>
	<div class="error" n:foreach="$formErrors as $error">{$error}</div>

	<p>
		{label name}Název{/label}<br>
		{input name class => "title"}
	</p>
	<p>
		{label url}URL{/label}<br>
		{input url}
	</p>
	<p>
		{label description}Popis (viditelný ve vyhledávačích u výsledku vyhledávání){/label}<br>
		{input description}
	</p>
	<p>
		{label text}Text{/label}<br>
		{input text}
	</p>
	<p>
		{input allowed} {label allowed}Povolit samostatné zobrazení jako článek{/label}
	</p>

	<p>{input s value => "Uložit"}</p>
</fieldset>

{/form}