{form $form}

<ul n:if="count($formErrors) > 0">
	<li n:foreach="$formErrors as $error">{$error}</li>
</ul>

<fieldset>
<table>
	<tr>
		<th>{label name}Jméno{/label}</th>
		<td>{input name size => 40}</td>
	</tr><tr>
		<th>{label surname}Příjmení{/label}</th>
		<td>{input surname size => 40}</td>
	</tr><tr>
		<th>{label mail}Mail{/label}</th>
		<td>{input mail size => 40}</td>
	</tr><tr>
		<th>{label username}Uživatelské jméno{/label}</th>
		<td>{input username size => 40}</td>
	</tr><tr>
		<th>{label password}Heslo{/label}</th>
		<td>{input password size => 40}</td>
	</tr>
</table>
</fieldset>

<p>{input s value => "Save"}</p>

{/form}