{form $form}

<fieldset>
	<div class="error" n:foreach="$formErrors as $error">{$error}</div>

	<p>
		{label name}Jméno{/label}<br>
		{input name}
	</p>
	<p>
		{label surname}Příjmení{/label}<br>
		{input surname}
	</p>
	<p>
		{label mail}Mail{/label}<br>
		{input mail}
	</p>
	<p>
		{label phone}Telefon{/label}<br>
		{input phone}
	</p>
	<p>
		{label username}Uživatelské jméno{/label}<br>
		{input username}
	</p>
	<p>
		{label password}Heslo{/label}<br>
		{input password}
	</p>

	<p>{input s value => "Uložit"}</p>
</fieldset>

{/form}