<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
	<title>{if isset($title)}{$title} :: {/if}Neuron</title>

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" type="text/javascript"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js" type="text/javascript"></script>
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css" type="text/css">

	{control css}
	{control js}
</head>

<body>
	<div class="container">
		<div class="span-6">
			<div class="box">
				<h2>Neuron</h2>

				<ul>
					<li><a href="{link Pages:}">Stránky</a></li>
					<li><a href="{link Users:}">Uživatelé</a></li>
				</ul>
			</div>

			<div class="box">
				{control userBox}
			</div>
		</div>

		<div class="span-18 last">
			<div class="box" style="background:white">
				{snippet flashes}
				<div class="{if $flash->type == 'error'}error{else}success{/if}" n:foreach="$flashes as $flash">{$flash->message}</div>
				{/snippet}

				<div id="content">
				{include #content}
				</div>
			</div>
		</div>
	</div>
</body>
</html>