<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<title>{ifset $title}{$title} - {/if}Neuron</title>

	<meta name="description" content="{$description}" n:ifset="$description">
	<meta name="keywords" content="{$keywords}" n:ifset="$keywords">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>

	{control css}
	{widget js}
</head>
<body>
	<div class="container">
		<div class="span-6">
			<div class="box">
				<h2><a href="{plink Homepage:}">Neuron</a></h2>

				{if $user->isLoggedIn()}
					<h3>Přihlášen {$user->identity->name} {$user->identity->surname}</h3>
					<ul>
						<li n:if="$user->isInRole('admin')"><a href="{plink :Admin:Pages:}">Administrace</a></li>
						<li><a href="{link logout!}">Odhlásit se</a></li>
					</ul>
				{else}
					<h3>Přihlásit se</h3>
					{control loginForm}
				{/if}
			</div>
		</div>

		<div class="span-18 last">
			<div class="box" style="background: white">
				{snippet flashes}
				<div class="{if $flash->type == 'error'}error{else}success{/if}" n:foreach="$flashes as $flash">{$flash->message}</div>
				{/snippet}

				@{include #content}
			</div>
		</div>

	
		<div class="span-24">
			<p>&copy; <a href="http://www.janmarek.net/">Jan Marek</a></p>
		</div>
	</div>
</body>
</html>
