{form $form}

<ul n:if="count($formErrors) > 0">
	<li n:foreach="$formErrors as $error">{$error}</li>
</ul>

<table>
	<tr>
		<td>{label name text => "Jméno"}</td>
		<td>{input name size => 50}</td>
	</tr><tr>
		<td>{label username text => "Uživatelské jméno"}</td>
		<td>{input username size => 50}</td>
	</tr><tr>
		<td>{label password text => "Heslo"}</td>
		<td>
			{input password size => 50}
			Pozor, políčko je při zadávání <strong>viditelné</strong>.
			{if $form->name === "editForm"}Pokud nechcete měnit heslo, nechte políčko prázdné.{/if}
		</td>
	</tr><tr>
		<td>{label mail text => "E-mail"}</td>
		<td>{input mail size => 50}</td>
	</tr><tr>
		<td>{label text text => "Text"}</td>
		<td>{input text rows => 20, cols => 90}</td>
	</tr>
</table>

<p>{input s value => "Uložit"}</p>

{/form}